"use client";

import { KindlingFooter } from "@/components/kindling-footer";

export default function TermsPage() {
  return (
    <main className="legal-page">
      <div className="legal-content">
        <span className="eyebrow">Legal</span>
        <h1>Terms of Service</h1>
        <p className="legal-updated">Last updated: April 26, 2026</p>

        <h2>1. Acceptance of Terms</h2>
        <p>
          By accessing or using Kindred Photos (&quot;Kindred,&quot; the &quot;Service&quot;), developed
          by Kindling Signal, you agree to be bound by these Terms of Service. If you
          do not agree, do not use the Service.
        </p>

        <h2>2. Description of Service</h2>
        <p>
          Kindred is a self-hosted household photo management application that uses
          AI to organize photos by people, places, and moments. Photos are stored on
          your Flickr account; processing occurs on your self-hosted server.
        </p>

        <h2>3. Accounts &amp; Households</h2>
        <p>
          Access to Kindred requires an account within a household. Households are
          created by an admin who connects their Flickr storage. Additional members
          join via invite codes generated by the admin.
        </p>
        <p>
          You are responsible for maintaining the security of your account credentials.
          You agree not to share your password or session tokens with anyone outside
          your household.
        </p>

        <h2>4. Your Content</h2>
        <p>
          You retain all ownership rights to your photos and content. Kindred does not
          claim any intellectual property rights over your photos. By using the Service,
          you grant Kindred permission to process your photos for the purpose of
          providing the Service (face recognition, object detection, scene classification).
        </p>

        <h2>5. Acceptable Use</h2>
        <p>You agree not to:</p>
        <ul>
          <li>Use the Service to store or distribute illegal content</li>
          <li>Attempt to gain unauthorized access to other households</li>
          <li>Reverse-engineer, decompile, or disassemble the Service</li>
          <li>Use the Service to harass, abuse, or harm others</li>
          <li>Circumvent rate limits, authentication, or security measures</li>
        </ul>

        <h2>6. Flickr Integration</h2>
        <p>
          Kindred integrates with Flickr for photo storage. Your use of Flickr is
          subject to Flickr&apos;s own Terms of Service and Privacy Policy. Kindred is not
          affiliated with or endorsed by Flickr or SmugMug, Inc.
        </p>

        <h2>7. Self-Hosted Nature</h2>
        <p>
          Kindred is designed to be self-hosted. You are responsible for the security,
          maintenance, and backup of your server infrastructure. Kindling Signal is not
          responsible for data loss resulting from server misconfiguration, hardware
          failure, or inadequate backups.
        </p>

        <h2>8. Disclaimer of Warranties</h2>
        <p>
          The Service is provided &quot;as is&quot; and &quot;as available&quot; without warranties of any
          kind, either express or implied. Kindling Signal does not warrant that the
          Service will be uninterrupted, secure, or error-free.
        </p>

        <h2>9. Limitation of Liability</h2>
        <p>
          To the maximum extent permitted by law, Kindling Signal shall not be liable
          for any indirect, incidental, special, consequential, or punitive damages
          arising from your use of the Service, including but not limited to loss of
          data, loss of photos, or inability to access the Service.
        </p>

        <h2>10. Open Source</h2>
        <p>
          Kindred Photos is released under the GNU Affero General Public License v3.0 (AGPL-3.0). You are free to use, modify,
          and distribute the software in accordance with the AGPL-3.0 license terms. If you modify and deploy
          Kindred as a network service, you must make your modified source code available
          to users of that service. The full
          license text is available in the project repository.
        </p>

        <h2>11. Changes to Terms</h2>
        <p>
          We may revise these Terms from time to time. Continued use of the Service
          after changes constitutes acceptance. We will make reasonable efforts to
          notify users of material changes.
        </p>

        <h2>12. Contact</h2>
        <p>
          Questions about these terms? Email{" "}
          <a href="mailto:sayhello@bykindling.com">sayhello@bykindling.com</a>.
        </p>
      </div>
      <KindlingFooter />
    </main>
  );
}
